version: '3'

services:
  web:
    build: ./  # Use the Dockerfile in the current directory
    expose:
      - 8000  # Expose the port where Gunicorn is running

  nginx:
    build:
      context: ./nginx  # Build the Nginx Dockerfile in the 'nginx' directory
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
    depends_on:
      - web  # Ensure that the 'web' service is started before Nginx
